apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: minio
    release: {{ .Release.Name }}
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
