apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-minio
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: minio
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: minio
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["minio", "server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.auth.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
