using Muntada.Rooms.Domain.Events;
using Muntada.Rooms.Domain.Invite;
using Muntada.Rooms.Domain.Participant;
using Muntada.Rooms.Domain.Series;
using Muntada.Rooms.Domain.Template;
using Muntada.SharedKernel.Domain;
using Stateless;

namespace Muntada.Rooms.Domain.Occurrence;

/// <summary>
/// Aggregate root representing a specific room instance at a scheduled time.
/// Can be standalone (one-off) or part of a <see cref="RoomSeries"/>.
/// Enforces a strict lifecycle state machine via the Stateless library.
/// </summary>
public class RoomOccurrence : AggregateRoot<RoomOccurrenceId>
{
    private StateMachine<RoomOccurrenceStatus, RoomTrigger>? _stateMachine;

    /// <summary>Gets the tenant that owns this occurrence.</summary>
    public string TenantId { get; private set; } = default!;

    /// <summary>Gets the parent series ID, or null for standalone rooms.</summary>
    public RoomSeriesId? RoomSeriesId { get; private set; }

    /// <summary>Gets the room title.</summary>
    public string Title { get; private set; } = default!;

    /// <summary>Gets the UTC scheduled start time.</summary>
    public DateTimeOffset ScheduledAt { get; private set; }

    /// <summary>Gets the IANA timezone identifier for display conversion.</summary>
    public string OrganizerTimeZoneId { get; private set; } = default!;

    /// <summary>Gets the UTC timestamp when the room went live, or null.</summary>
    public DateTimeOffset? LiveStartedAt { get; private set; }

    /// <summary>Gets the UTC timestamp when the room ended, or null.</summary>
    public DateTimeOffset? LiveEndedAt { get; private set; }

    /// <summary>Gets the current lifecycle status.</summary>
    public RoomOccurrenceStatus Status { get; private set; }

    /// <summary>Gets the designated moderator for this room.</summary>
    public ModeratorAssignment? ModeratorAssignment { get; private set; }

    /// <summary>Gets the room settings (may override template defaults).</summary>
    public RoomSettings Settings { get; private set; } = default!;

    /// <summary>Gets the grace period timeout in seconds (default 300 = 5 min).</summary>
    public int GracePeriodSeconds { get; private set; } = 300;

    /// <summary>Gets the UTC timestamp when grace period started, or null.</summary>
    public DateTimeOffset? GraceStartedAt { get; private set; }

    /// <summary>Gets whether this occurrence has been cancelled.</summary>
    public bool IsCancelled { get; private set; }

    /// <summary>Gets the user who created this occurrence.</summary>
    public string CreatedBy { get; private set; } = default!;

    /// <summary>Gets the collection of invites for this occurrence.</summary>
    public ICollection<RoomInvite> Invites { get; private set; } = new List<RoomInvite>();

    /// <summary>Gets the collection of participant states for this occurrence.</summary>
    public ICollection<RoomParticipantState> Participants { get; private set; } = new List<RoomParticipantState>();

    private RoomOccurrence() { }

    /// <summary>
    /// Creates a new standalone room occurrence (not linked to a series).
    /// </summary>
    public static RoomOccurrence CreateStandalone(
        string tenantId,
        string title,
        DateTimeOffset scheduledAt,
        string organizerTimeZoneId,
        RoomSettings settings,
        string createdBy,
        int gracePeriodSeconds = 300)
    {
        ValidateTitle(title);

        var occurrence = new RoomOccurrence
        {
            Id = RoomOccurrenceId.New(),
            TenantId = tenantId,
            RoomSeriesId = null,
            Title = title,
            ScheduledAt = scheduledAt,
            OrganizerTimeZoneId = organizerTimeZoneId,
            Status = RoomOccurrenceStatus.Draft,
            Settings = settings,
            GracePeriodSeconds = gracePeriodSeconds,
            CreatedBy = createdBy,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };

        return occurrence;
    }

    /// <summary>
    /// Creates a room occurrence from a series (generated by background job).
    /// </summary>
    public static RoomOccurrence CreateFromSeries(
        string tenantId,
        RoomSeriesId seriesId,
        string title,
        DateTimeOffset scheduledAt,
        string organizerTimeZoneId,
        RoomSettings settings,
        string createdBy,
        int gracePeriodSeconds = 300)
    {
        ValidateTitle(title);

        return new RoomOccurrence
        {
            Id = RoomOccurrenceId.New(),
            TenantId = tenantId,
            RoomSeriesId = seriesId,
            Title = title,
            ScheduledAt = scheduledAt,
            OrganizerTimeZoneId = organizerTimeZoneId,
            Status = RoomOccurrenceStatus.Draft,
            Settings = settings,
            GracePeriodSeconds = gracePeriodSeconds,
            CreatedBy = createdBy,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Assigns a moderator and transitions the room from Draft to Scheduled.
    /// </summary>
    /// <param name="moderatorUserId">The user ID of the designated moderator.</param>
    public void AssignModeratorAndSchedule(string moderatorUserId)
    {
        ModeratorAssignment = ModeratorAssignment.Create(moderatorUserId);
        GetStateMachine().Fire(RoomTrigger.Schedule);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Changes the moderator. Room must be in Draft or Scheduled status.
    /// </summary>
    /// <param name="newModeratorUserId">The user ID of the new moderator.</param>
    public void ChangeModerator(string newModeratorUserId)
    {
        if (Status != RoomOccurrenceStatus.Draft && Status != RoomOccurrenceStatus.Scheduled)
            throw new InvalidOperationException(
                $"Cannot change moderator when room is in {Status} status. Must be Draft or Scheduled.");

        ModeratorAssignment = ModeratorAssignment.Create(newModeratorUserId);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Transitions the room to Live when the first participant connects.
    /// </summary>
    public void GoLive()
    {
        GetStateMachine().Fire(RoomTrigger.FirstParticipantJoins);
        LiveStartedAt = DateTimeOffset.UtcNow;
        UpdatedAt = DateTimeOffset.UtcNow;

        AddDomainEvent(new RoomStatusChangedDomainEvent(
            Guid.NewGuid(), DateTimeOffset.UtcNow,
            Id.Value, RoomOccurrenceStatus.Scheduled.ToString(), RoomOccurrenceStatus.Live.ToString()));
    }

    /// <summary>
    /// Transitions the room to Grace when the moderator disconnects.
    /// </summary>
    public void StartGracePeriod()
    {
        GetStateMachine().Fire(RoomTrigger.ModeratorDisconnects);
        GraceStartedAt = DateTimeOffset.UtcNow;
        ModeratorAssignment?.RecordDisconnect();
        UpdatedAt = DateTimeOffset.UtcNow;

        AddDomainEvent(new RoomStatusChangedDomainEvent(
            Guid.NewGuid(), DateTimeOffset.UtcNow,
            Id.Value, RoomOccurrenceStatus.Live.ToString(), RoomOccurrenceStatus.Grace.ToString()));
    }

    /// <summary>
    /// Returns the room from Grace to Live when the moderator reconnects.
    /// </summary>
    public void ModeratorReconnects()
    {
        GetStateMachine().Fire(RoomTrigger.ModeratorReconnects);
        GraceStartedAt = null;
        ModeratorAssignment?.RecordReconnect();
        UpdatedAt = DateTimeOffset.UtcNow;

        AddDomainEvent(new RoomStatusChangedDomainEvent(
            Guid.NewGuid(), DateTimeOffset.UtcNow,
            Id.Value, RoomOccurrenceStatus.Grace.ToString(), RoomOccurrenceStatus.Live.ToString()));
    }

    /// <summary>
    /// Hands over moderator control to another user during Grace period.
    /// Transitions the room back to Live.
    /// </summary>
    /// <param name="newModeratorUserId">The user ID of the new moderator.</param>
    public void HandoverModerator(string newModeratorUserId)
    {
        if (Status != RoomOccurrenceStatus.Grace)
            throw new InvalidOperationException("Moderator handover is only allowed during Grace period.");

        var oldModeratorUserId = ModeratorAssignment?.UserId ?? "unknown";
        ModeratorAssignment = ModeratorAssignment.Create(newModeratorUserId);
        GetStateMachine().Fire(RoomTrigger.ModeratorReconnects);
        GraceStartedAt = null;
        UpdatedAt = DateTimeOffset.UtcNow;

        AddDomainEvent(new RoomStatusChangedDomainEvent(
            Guid.NewGuid(), DateTimeOffset.UtcNow,
            Id.Value, RoomOccurrenceStatus.Grace.ToString(), RoomOccurrenceStatus.Live.ToString()));
    }

    /// <summary>
    /// Ends the room (grace expired, moderator action, or all participants left).
    /// </summary>
    public void End()
    {
        GetStateMachine().Fire(RoomTrigger.EndRoom);
        LiveEndedAt = DateTimeOffset.UtcNow;
        GraceStartedAt = null;
        UpdatedAt = DateTimeOffset.UtcNow;

        AddDomainEvent(new RoomStatusChangedDomainEvent(
            Guid.NewGuid(), DateTimeOffset.UtcNow,
            Id.Value, "Live/Grace", RoomOccurrenceStatus.Ended.ToString()));
    }

    /// <summary>
    /// Archives the room per retention policy.
    /// </summary>
    public void Archive()
    {
        GetStateMachine().Fire(RoomTrigger.RetentionExpires);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Updates single-occurrence fields (title, settings, cancellation).
    /// </summary>
    public void UpdateOverride(string? title, RoomSettings? settings, bool? isCancelled)
    {
        if (Status == RoomOccurrenceStatus.Ended || Status == RoomOccurrenceStatus.Archived)
            throw new InvalidOperationException("Cannot modify a room that has ended or been archived.");

        if (title is not null)
        {
            ValidateTitle(title);
            Title = title;
        }

        if (settings is not null)
            Settings = settings;

        if (isCancelled.HasValue)
            IsCancelled = isCancelled.Value;

        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Checks whether a given status transition is permitted.
    /// </summary>
    /// <param name="trigger">The trigger to check.</param>
    /// <returns>True if the transition is allowed.</returns>
    public bool CanFire(RoomTrigger trigger) => GetStateMachine().CanFire(trigger);

    private StateMachine<RoomOccurrenceStatus, RoomTrigger> GetStateMachine()
    {
        if (_stateMachine is not null) return _stateMachine;

        _stateMachine = new StateMachine<RoomOccurrenceStatus, RoomTrigger>(
            () => Status,
            s => Status = s);

        _stateMachine.Configure(RoomOccurrenceStatus.Draft)
            .Permit(RoomTrigger.Schedule, RoomOccurrenceStatus.Scheduled);

        _stateMachine.Configure(RoomOccurrenceStatus.Scheduled)
            .Permit(RoomTrigger.FirstParticipantJoins, RoomOccurrenceStatus.Live);

        _stateMachine.Configure(RoomOccurrenceStatus.Live)
            .Permit(RoomTrigger.ModeratorDisconnects, RoomOccurrenceStatus.Grace)
            .Permit(RoomTrigger.EndRoom, RoomOccurrenceStatus.Ended);

        _stateMachine.Configure(RoomOccurrenceStatus.Grace)
            .Permit(RoomTrigger.ModeratorReconnects, RoomOccurrenceStatus.Live)
            .Permit(RoomTrigger.EndRoom, RoomOccurrenceStatus.Ended);

        _stateMachine.Configure(RoomOccurrenceStatus.Ended)
            .Permit(RoomTrigger.RetentionExpires, RoomOccurrenceStatus.Archived);

        return _stateMachine;
    }

    private static void ValidateTitle(string title)
    {
        if (string.IsNullOrWhiteSpace(title) || title.Length < 3 || title.Length > 200)
            throw new SharedKernel.Domain.Exceptions.ValidationException(
                "Validation", "Room title must be between 3 and 200 characters.");
    }
}

/// <summary>
/// Triggers for the room occurrence state machine.
/// </summary>
public enum RoomTrigger
{
    /// <summary>Moderator assigned and time set — transition Draft → Scheduled.</summary>
    Schedule,

    /// <summary>First participant connects — transition Scheduled → Live.</summary>
    FirstParticipantJoins,

    /// <summary>Moderator disconnects — transition Live → Grace.</summary>
    ModeratorDisconnects,

    /// <summary>Moderator reconnects — transition Grace → Live.</summary>
    ModeratorReconnects,

    /// <summary>Grace expires, moderator ends, or all leave — transition Live/Grace → Ended.</summary>
    EndRoom,

    /// <summary>Retention policy triggers — transition Ended → Archived.</summary>
    RetentionExpires
}
