apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rabbitmq-username: {{ .Values.auth.username | quote }}
  rabbitmq-password: {{ .Values.auth.password | quote }}
  rabbitmq-erlang-cookie: {{ .Values.auth.erlangCookie | quote }}
