apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
    release: {{ .Release.Name }}
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
