replicas: 1

image:
  repository: rabbitmq
  tag: "3-management-alpine"

auth:
  username: muntada
  password: dev-password
  vhost: muntada

erlangCookie: dev-erlang-cookie

diskFreeLimit: "1GB"
memoryHighWatermark: "0.6"

storage:
  storageClass: standard
  size: 5Gi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
