apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-livekit-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  api-key: {{ .Values.auth.apiKey | b64enc | quote }}
  api-secret: {{ .Values.auth.apiSecret | b64enc | quote }}
