apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-livekit
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: livekit
    release: {{ .Release.Name }}
  ports:
    - port: 7880
      targetPort: 7880
      name: http
    - port: 7881
      targetPort: 7881
      name: rtc-tcp
    - port: 7882
      targetPort: 7882
      name: rtc-udp
      protocol: UDP
