@Muntada.Api_HostAddress = http://localhost:5219

#if (EnableOpenAPI)
GET {{Muntada.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{Muntada.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
