apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sql-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: sql-server
    release: {{ .Release.Name }}
  ports:
    - port: 1433
      targetPort: 1433
      name: sql
