apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-sql-server
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-sql-server
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: sql-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: sql-server
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: sql-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 1433
              name: sql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-sql-secret
                  key: sa-password
            - name: MSSQL_PID
              value: {{ .Values.mssqlPid | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: sql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
