// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muntada.Rooms.Infrastructure;

#nullable disable

namespace Muntada.Rooms.Migrations
{
    [DbContext(typeof(RoomsDbContext))]
    [Migration("20260404203509_InitialRoomsSchema")]
    partial class InitialRoomsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rooms")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Muntada.Rooms.Domain.Invite.RoomInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InviteType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InvitedUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InviteToken")
                        .IsUnique();

                    b.HasIndex("RoomOccurrenceId", "Status");

                    b.ToTable("RoomInvites", "rooms");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Occurrence.RoomOccurrence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GracePeriodSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("GraceStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LiveEndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LiveStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrganizerTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoomSeriesId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomSeriesId");

                    b.HasIndex("TenantId", "ScheduledAt");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("RoomOccurrences", "rooms");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Participant.RoomParticipantState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AudioState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveKitParticipantId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoomOccurrenceId", "LeftAt");

                    b.ToTable("RoomParticipantStates", "rooms");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Recording.Recording", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("LiveKitEgressId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoomOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("S3Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoomOccurrenceId");

                    b.HasIndex("TenantId");

                    b.ToTable("Recordings", "rooms");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Series.RoomSeries", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrganizerTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecurrenceRule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("RoomSeries", "rooms");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Template.RoomTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("RoomTemplates", "rooms");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Occurrence.RoomOccurrence", b =>
                {
                    b.OwnsOne("Muntada.Rooms.Domain.Occurrence.ModeratorAssignment", "ModeratorAssignment", b1 =>
                        {
                            b1.Property<string>("RoomOccurrenceId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTimeOffset>("AssignedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ModeratorAssignedAt");

                            b1.Property<DateTimeOffset?>("DisconnectedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ModeratorDisconnectedAt");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ModeratorUserId");

                            b1.HasKey("RoomOccurrenceId");

                            b1.ToTable("RoomOccurrences", "rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomOccurrenceId");
                        });

                    b.OwnsOne("Muntada.Rooms.Domain.Template.RoomSettings", "Settings", b1 =>
                        {
                            b1.Property<string>("RoomOccurrenceId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<bool>("AllowGuestAccess")
                                .HasColumnType("bit")
                                .HasColumnName("AllowGuestAccess");

                            b1.Property<bool>("AllowRecording")
                                .HasColumnType("bit")
                                .HasColumnName("AllowRecording");

                            b1.Property<bool>("AllowTranscription")
                                .HasColumnType("bit")
                                .HasColumnName("AllowTranscription");

                            b1.Property<bool>("AutoStartRecording")
                                .HasColumnType("bit")
                                .HasColumnName("AutoStartRecording");

                            b1.Property<string>("DefaultTranscriptionLanguage")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DefaultTranscriptionLanguage");

                            b1.Property<int>("MaxParticipants")
                                .HasColumnType("int")
                                .HasColumnName("MaxParticipants");

                            b1.HasKey("RoomOccurrenceId");

                            b1.ToTable("RoomOccurrences", "rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomOccurrenceId");
                        });

                    b.Navigation("ModeratorAssignment");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Recording.Recording", b =>
                {
                    b.OwnsMany("Muntada.Rooms.Domain.Recording.Transcript", "Transcripts", b1 =>
                        {
                            b1.Property<string>("RecordingId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("S3Path")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("TextS3Path")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("RecordingId", "Id");

                            b1.ToTable("Transcript", "rooms");

                            b1.WithOwner()
                                .HasForeignKey("RecordingId");
                        });

                    b.Navigation("Transcripts");
                });

            modelBuilder.Entity("Muntada.Rooms.Domain.Template.RoomTemplate", b =>
                {
                    b.OwnsOne("Muntada.Rooms.Domain.Template.RoomSettings", "Settings", b1 =>
                        {
                            b1.Property<string>("RoomTemplateId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<bool>("AllowGuestAccess")
                                .HasColumnType("bit")
                                .HasColumnName("AllowGuestAccess");

                            b1.Property<bool>("AllowRecording")
                                .HasColumnType("bit")
                                .HasColumnName("AllowRecording");

                            b1.Property<bool>("AllowTranscription")
                                .HasColumnType("bit")
                                .HasColumnName("AllowTranscription");

                            b1.Property<bool>("AutoStartRecording")
                                .HasColumnType("bit")
                                .HasColumnName("AutoStartRecording");

                            b1.Property<string>("DefaultTranscriptionLanguage")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DefaultTranscriptionLanguage");

                            b1.Property<int>("MaxParticipants")
                                .HasColumnType("int")
                                .HasColumnName("MaxParticipants");

                            b1.HasKey("RoomTemplateId");

                            b1.ToTable("RoomTemplates", "rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomTemplateId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
