apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: muntada-api
    release: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.api.port }}
      name: http
