apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  sql-connection-string: {{ .Values.api.connectionStrings.sqlServer | default "" | quote }}
  redis-connection-string: {{ .Values.api.connectionStrings.redis | default "" | quote }}
  rabbitmq-connection-string: {{ .Values.api.connectionStrings.rabbitmq | default "" | quote }}
