replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: "2022-latest"

mssqlPid: Standard
saPassword: "CHANGE_ME_IN_SEALED_SECRET"

storage:
  storageClass: managed-premium
  size: 100Gi

resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "4"
    memory: "16Gi"
