replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: "2022-latest"

mssqlPid: Developer
saPassword: "Dev@Password123!"

storage:
  storageClass: standard
  size: 10Gi

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
